[package]
name = "wstcp"
version = "0.3.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "WebSocket to TCP proxy server"
homepage = "https://github.com/sile/wstcp"
repository = "https://github.com/sile/wstcp"
readme = "README.md"
keywords = ["websocket", "proxy", "tcp"]
license = "MIT"
edition = "2024"
rust-version = "1.88"

[dependencies]
env_logger = "0.11"
log = "0.4"
noargs = "0.4"
shiguredo_websocket = "2026"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "time"] }
