name: Release

on:
  push:
    tags:
      - '*'

jobs:
  github:
    name: 'GitHub Release'
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: rustup update stable
      - run: rustup default stable
      - run: rustup target add x86_64-unknown-linux-musl
      - name: Run cargo build
        run: cargo build --release --target=x86_64-unknown-linux-musl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            --title "v${{ steps.get_version.outputs.VERSION }}" \
            --generate-notes

      - name: Upload Linux Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv target/x86_64-unknown-linux-musl/release/wstcp wstcp-${{ steps.get_version.outputs.VERSION }}.linux
          gh release upload ${{ steps.get_version.outputs.VERSION }} \
            wstcp-${{ steps.get_version.outputs.VERSION }}.linux
